name: Verify Eclipse Platform SWT Build
on:
  workflow_dispatch:

jobs:
  build-swt:
    runs-on: ubuntu-latest
    name: Verify Linux
    steps:
    - name: Checkout tycho code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       path: 'tycho'
       repository: 'eclipse-tycho/tycho'
       fetch-depth: 0
    - name: Checkout platform code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
       path: 'swt'
       submodules: 'recursive'
       lfs: true
       repository: 'eclipse-platform/eclipse.platform.swt'
       fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        java-version: |
            11
            21
            17
        distribution: 'temurin'
    #- name: Cache local Maven repository
    #  uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
    #  with:
    #    path: ~/.m2/repository
    #    key: ${{ runner.os }}-maven-verify-platform-swt-${{ hashFiles('**/pom.xml', '**/*.target') }}
    #    restore-keys: |
    #      ${{ runner.os }}-maven-verify-platform-swt-
    - name: Set up Maven
      uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
      with:
        maven-version: 3.9.9
    - name: Build Tycho
      working-directory: 'tycho'
      run: >- 
        mvn -U -V -e -B -ntp
        -DskipTests
        --file pom.xml
        -T1C
        clean install
    - name: Run Platform SWT Build
      working-directory: 'swt'
      shell: bash
      run: >- 
        mvn
        -ntp
        --batch-mode
        -Pbuild-individual-bundles
        -Pbree-libs
        -DskipTests
        -Dtycho.version=$(mvn help:evaluate -f ../tycho -Dexpression=project.version -q -DforceStdout)
        -T1C
        clean verify
